#!/bin/bash

set -xe

mkdir libs
cd libs
git clone https://github.com/TupleAustin/access-policy
git clone https://github.com/peerigon/angular-expressions
git clone https://github.com/mikeerickson/cd-messenger
git clone https://github.com/hunterloftis/cryo
git clone https://github.com/skoranga/node-dns-sync
git clone https://github.com/mde/ejs
git clone https://github.com/mysticatea/eslint-utils
git clone https://github.com/jxson/front-matter
git clone https://github.com/tj/node-growl#readme
git clone https://github.com/gruntjs/grunt
git clone https://github.com/handsontable/formula-parser
git clone https://github.com/mafintosh/is-my-json-valid
git clone https://github.com/claudioc/jingo
git clone https://github.com/nodeca/js-yaml
git clone https://github.com/daxingplay/kmc
git clone https://github.com/c58/marsdb
git clone https://github.com/josdejong/mathjs
git clone https://github.com/mateodelnorte/meta-git
git clone https://github.com/floatinghotpot/mixin-pro
git clone https://github.com/modjs/mod
git clone https://github.com/matthewkastor/modulify
git clone https://github.com/milojs/proto
git clone https://github.com/louischatriot/mongo-edit
git clone https://github.com/mongo-express/mongo-express
git clone https://github.com/fresheneesz/mongo-parse
git clone https://github.com/mongodb-js/query-parser
git clone https://github.com/mccormicka/mongoosemask
git clone https://github.com/expressjs/morgan
git clone https://github.com/4y0/mosc
git clone https://github.com/mahdaen/node-import
git clone https://github.com/mithunsatheesh/node-rules
git clone https://github.com/luin/serialize
git clone https://github.com/mmckegg/notevil
git clone https://github.com/brianc/node-postgres
git clone https://github.com/Agoric/realms-shim
git clone https://github.com/MoOx/reduce-css-calc/
git clone https://github.com/hacksparrow/safe-eval
git clone https://github.com/commenthol/safer-eval
git clone https://github.com/gf3/sandbox
git clone https://github.com/commenthol/serialize-to-js
git clone https://github.com/rhysd/Shiba
git clone https://github.com/browserify/static-eval
git clone https://github.com/thenables/thenify
git clone https://github.com/fabiosantoscode/value-censorship
git clone https://github.com/tj/node-growl
git clone https://github.com/milojs/proto mol-proto
git clone "git://github.com/fibo/algebra.git"
git clone "git://github.com/mattdesl/array-range.git"
git clone "https://github.com/zhiyelee/array.chunk.git"
git clone "http://github.com/maxogden/concat-stream.git"
git clone "https://github.com/kevinbeaty/fs-promise.git"
git clone "https://github.com/ryanaghdam/has-key-deep.git"
git clone "https://github.com/mathiasbynens/he.git"
git clone "https://github.com/substack/identity-function.git"
git clone "https://github.com/gummesson/is-empty-object.git"
git clone "git://github.com/blakeembrey/is-generator.git"
git clone "https://github.com/then/is-promise.git"
git clone "https://github.com/dcousens/is-sorted.git"
git clone "git@github.com:stevemao/left-pad.git"
git clone "git+ssh://git@github.com/vladgolubev/missing-deep-keys.git"
git clone "git://github.com/mikolalysenko/ndarray.git"
git clone "https://github.com/rvagg/node-du.git"
git clone "git://github.com/isaacs/node-glob.git"
git clone "git://github.com/dodo/node-slug.git"
git clone "https://github.com/brycebaril/node-stream-spigot"
git clone "https://github.com/fibo/not-defined.git"
git clone "git://github.com/isaacs/once"
git clone "https://github.com/ycmjason/pad-left-simple.git"
git clone "https://github.com/ErikOnBike/parse-next-json-value"
git clone "https://github.com/timruffles/periods.git"
git clone "https://github.com/nettofarah/property-validator.git"
git clone "https://github.com/Atinux/schema-inspector.git"
git clone "git://github.com/fibo/static-props.git"
git clone "https://github.com/mcollina/syncthrough.git"
git clone "git@github.com:brycebaril/through2-map.git"
git clone "https://github.com/rvagg/through2.git"
git clone "https://github.com/mafintosh/unordered-array-remove.git"
git clone "https://github.com/landau/zipmap.git"
git clone "https://github.com/jonschlinkert/arr-diff"
git clone "https://github.com/jonschlinkert/arr-flatten"
git clone "https://github.com/jonschlinkert/array-first"
git clone "https://github.com/jonschlinkert/array-last"
git clone "https://github.com/jonschlinkert/deep-bind"
git clone "https://github.com/bendrucker/document-ready"
git clone "git://github.com/Nijikokun/file-size.git"
git clone "https://github.com/jonschlinkert/get-value"
git clone "https://github.com/doowb/group-array"
git clone "https://github.com/jonschlinkert/has-value"
git clone "https://github.com/jonschlinkert/in-array"
git clone "https://github.com/jonschlinkert/is-number"
git clone "https://github.com/jonschlinkert/normalize-pkg"
git clone "https://github.com/jonschlinkert/pad-left"
git clone "git://github.com/isaacs/rimraf.git"
git clone "https://github.com/sergejmueller/rtrim"
git clone "https://github.com/jonschlinkert/set-value"
git clone "https://github.com/jonschlinkert/time-stamp"
